name: 📝 deploy demo

on:
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    name: 🚀 Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Checkout
        uses: actions/checkout@v4
      - name: 🟢 Node
        uses: actions/setup-node@v3
        with:
          node-version: 22.21.1
          registry-url: 'https://registry.npmjs.org'
      - name: 🕵 Yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: 🏗 Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build-demo
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './demo'
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
